### ISSUE TITLE
Support custom game locations

### ISSUE THREAD

**Issue by mannaggacardarell** [moritzruth/among-us-mod-manager#1]
Close if u have installed among us on a different path

**Comment by moritzruth** [comment]
Sorry, I don’t quite understand what you mean.

**Comment by mannaggacardarell** [comment]
https://prnt.sc/zqm63p

**Comment by moritzruth** [comment]
This is planned.

**Comment by moritzruth** [comment]
[Available in v1.2.0](https://github.com/moritzruth/among-us-mod-manager/releases/tag/v1.2.0)
