### ISSUE TITLE
Integration of the Town of Us Mod

### ISSUE THREAD

**Issue by Nubanzi** [moritzruth/among-us-mod-manager#2]
Hi.

Is ist Possible to integrate the [Town of Us Mod](https://github.com/slushiegoose/Town-Of-Us)? The installation of the mod is similar to the other mods supported by this mod manager. Tonw of Us comes with a ton of new roles.

I would appreciate your feedback!

**Comment by moritzruth** [comment]
It’s now available in [v1.3.0](https://github.com/moritzruth/among-us-mod-manager/releases/tag/v1.3.0).
