### ISSUE TITLE
Town of Impostors and The other Roles

### ISSUE THREAD

**Issue by Nubanzi** [moritzruth/among-us-mod-manager#3]
Hi. Is it possible that you add Town of Impostors mod and The other Roles mod?

Town of Impostors already works with the new game version.
https://github.com/AJMix/TownOfImpostors

The other Roles still needs to be updated. //Edit: Other Roles works with new update
https://github.com/Eisbison/TheOtherRoles/releases

Appreciate your work!!

**Comment by moritzruth** [comment]
I’ll look into it :+1:

**Comment by moritzruth** [comment]
Just added them.
