### ISSUE TITLE
The purpose/der Zweck

### ISSUE THREAD

**Issue by Maryversal** [moritzruth/among-us-mod-manager#6]
I dont understand the purpose of this mod/ Ich verstehe den Zweck der Mod nicht

**Comment by moritzruth** [comment]
Among Us Mod Manager isn't a mod by itself. It's a tool which simplifies installing other, already existing mods, namely:
- Town of Us by slushiegoose
- Town of Impostors by AJMix
- The Other Roles by Eisbison
